name: currency_task
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl:

  cupertino_icons: ^1.0.2
  #State management
  flutter_bloc: ^8.1.3
  #Dependency injection
  injectable: ^2.3.2
  get_it: ^7.6.4
  #local database
  sqflite: ^2.3.0
  #http
  http: ^1.1.0
  #Comparing objects
  equatable: ^2.0.5
  #Nav bar
  google_nav_bar: ^5.0.6
  #Cached network image
  cached_network_image: ^3.3.0
  #Json theme
  json_theme: ^6.3.0
  #chart
  fl_chart: ^0.64.0
  #Path
  path: ^1.8.3
  #Connection check
  connectivity_plus: ^5.0.0
  #Mockicto
  mockito: ^5.4.2
  #functional
  dartz: ^0.10.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  test: ^1.24.3
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.4
  injectable_generator: ^2.4.1


flutter:
  uses-material-design: true
  assets:
    - assets/appainter_theme.json
